name: Build release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout source
        uses: actions/checkout@v4
        

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build
        run: |
          ./gradlew clean assembleRelease

      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v4
        with:
            name: ABC
            path: "app/build/outputs/apk/release/*-release*.apk"
